# -*- coding: utf-8 -*-
"""Licencing_System

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vjc_O6DonpOoAk8MWGAAzuIu74x5muCQ
"""

# Licencing_System

from datetime import date,datetime

webs=[]

class Customer:
  def __init__(self,name,password,email,address,subscription,renewal_date):
    self.name=name
    self.password=password
    self.email=email
    self.address=address
    self.subscription=subscription
    self.renewal_date=renewal_date

  def get_name(self):
    return self.name

  def get_password(self):
    return self.password

  def get_email(self):
    return self.email  

  def get_address(self):
    return self.address

  def get_subscription(self):
    return self.subscription

  def get_renewal_date(self):
    return self.renewal_date  

  def change_plan(self,new_plan):
    if new_plan.get_plan_name()=="Single" and self.get_subscription().get_no_website()>1:
       print("Found more than one website,to avail Single plan the number of website should be one, remove the unwanted websites and than degrade")
    elif new_plan.get_plan_name()=="Plus" and self.get_subscription().get_no_website()>3:
       print("Found more than three website,to avail Plus plan the number of website should be 3 or less than 3, remove the unwanted websites and than degrade")
    else:     
        self.subscription=new_plan
        self.renewal_date=date(self.get_renewal_date().year+1,self.get_renewal_date().month,self.get_renewal_date().day) 

  def subscribe_plan(self,subscription):
    self.subscription=subscription
    self.renewal_date=renewal_date


class Plan:
  def __init__(self,plan_name,no_website_allowance,price):
     self.plan_name=plan_name
     self.price=price
     self.no_website_allowance=no_website_allowance

  def get_plan_name(self):
     return self.plan_name

  def get_price(self):
     return self.price

  def get_no_website(self):
     return self.no_website_allowance

  def increment_no_website(self):
    self.no_website_allowance=self.no_website_allowance+1 

  def decrement_no_website(self):
    if self.no_website_allowance<1:
      print("You dont have any website attached")
    else:   
      self.no_website_allowance=self.no_website_allowance-1    

             
class Website:
  def __init__(self,url,customer):
    self.url=url
    self.customer=customer

  def get_urls(self):
    return self.url

  def get_customer(self):
    return self.customer

  def add_website(self,new_url):
    if len(self.get_urls())==1 and (self.get_customer().get_subscription().get_plan_name()=="Single"):
       print("Cannot add more than 1 websites in the 'Single' plan")
    elif len(self.get_urls())==3 and (self.get_customer().get_subscription().get_plan_name()=="Plus"):
       print("Cannot add more than 3 websites in the 'Single' plan")
    else:
      if new_url in self.url:
        print("URL already present in your subscription")
      else:  
        url.append(new_url)
        self.get_customer().get_subscription().increment_no_website()

  def remove_url(self,rem_url):
     if rem_url in self.url:
       self.url.remove(rem_url)
       self.get_customer().get_subscription().decrement_no_website()
     else:
       print("Url in not present...")

  def print_details(self):
    print("Customer Details ")
    print("*"*50)
    print("Name of the customer : ",self.get_customer().get_name())
    print("Email : ",self.get_customer().get_email())
    print("Address : ",self.get_customer().get_address())
    print("Renewal date : ",self.get_customer().get_renewal_date())
    print("Subscription Details")
    print("*"*50)
    print("Current Plan Activated : ",self.get_customer().get_subscription().get_plan_name())
    print("Plan Price : ",self.get_customer().get_subscription().get_price())
    print("Number of Website : ",self.get_customer().get_subscription().get_no_website())
 
    print("Urls Attached")
    print("*"*50)
    for i in self.url:
      print(i)
while True: 
    print("1, Want to subscribe")
    print("2, Add Website ")
    print("3, Remove url")
    print("4, Change Plan")
    print("5, Print details of customer")            
    single_plan=Plan("Single",0,"$49")
    plus_plan=Plan("Plus",0,"$99")
    infinite_plan=Plan("Infinite",0,"$249")

    Choice=int(input("Enter your choice : "))
    if Choice==1:
       print("Plans Available")
       print("1, Single  1 website $49 ")
       print("2, Plus  3 website $99 ")
       print("3, Unlimited Websites $249 ")
       Choice1=int(input("Enter you plan choice : "))
       if Choice1==1:
         plan=single_plan
       elif Choice1==2:
         plan=plus_plan
       elif Choice1==3:
         plan=infinite_plan    
       name=input("Enter your name : ")
       password=input("Enter your password : ")
       email=input("Enter Email : ")
       address=input("Enter address : ")
       cust=Customer(name,password,email,address,plan,date.today())
       Choice2=int(input("Want to add website now? press 1 for yes : "))
       if Choice2==1:
          if plan.get_plan_name()=="Single":
            url=[]
            url.append(input("Enter URL : "))
            plan.increment_no_website()
          elif plan.get_plan_name()=="Plus":
            url=[]
            for i in range(3):
               Choice4=int(input("Want to add url? press 1 for NO or 0 for YES: "))
               if Choice4==1:
                 break
               url.append(input("Enter url : "))
               plan.increment_no_website()
             
          elif plan.get_plan_name()=="Infinite":
               url=[]
               while True:
                   if int(input("Want to continue? press 0 for NO : "))==0:
                       break
                   url.append(input("Enter url : "))
                   plan.increment_no_website()
             
          
          web=Website(url,cust)
          webs.append(web)
    elif Choice==2:
       name=input("Enter name : ")
       password=input("Enter password : ")
       for web in webs:
           if (web.get_customer().get_name()==name) and (web.get_customer().get_password()==password):
               url_name=input("Enter url to add : ")
               web.add_website(url_name)
               break
    elif Choice==3:
       name=input("Enter name : ")
       password=input("Enter password : ")
       for web in webs:
            if (web.get_customer().get_name()==name) and (web.get_customer().get_password()==password):
               url_name=input("Enter url to remove : ")
               web.remove_url(url_name)
               break
    elif Choice==4:
       name=input("Enter name : ")
       password=input("Enter password : ")
       for web in webs:
            if (web.get_customer().get_name()==name) and (web.get_customer().get_password()==password):
                   print("Plans Available")
                   print("1, Single  1 website $49 ")
                   print("2, Plus  3 website $99 ")
                   print("3, Unlimited Websites $249 ")
                   Choice1=int(input("Enter you plan choice : "))
                   current_plan_websites=web.get_customer().get_subscription().get_no_website()
                   if Choice1==1:
                      plan=Plan("Single",current_plan_websites,"$49")
                   elif Choice1==2:
                      plan=Plan("Plus",current_plan_websites,"$99")
                   elif Choice1==3:
                       plan=Plan("Infinite",current_plan_websites,"$249")
                   web.get_customer().change_plan(plan)
    elif Choice==5:
       name=input("Enter name : ")
       password=input("Enter password : ")
       for web in webs:
            if (web.get_customer().get_name()==name) and (web.get_customer().get_password()==password):
                web.print_details()
                break
       else:
         print("No such customer exists!")     
    Choice5=int(input("Want to do more operation? press 1 for No : "))
    if Choice5==1:
      break   

for web in webs:
  web.print_details()

