# -*- coding: utf-8 -*-
"""Secret Santa

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O07c2GhfzHrM2LafzHhkZ_A6-JESuSeL
"""

"""newSanta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_0eD77RzXvjy0YpzsZTrmqNUs7sXPk-9
"""
# Secret Santa


import os
import random
import csv
i=0
li=[]
dic={}
dic1={}
dic2={}
while i==0:
    li.append([i for i in input().split(",")])
    i=int(input("want to add more names ? press 0 to continue"))

if (os.path.exists(os.getcwd()+"/secretSanta.csv")) and (os.stat(os.getcwd()+"/secretSanta.csv").st_size != 0):
  rows=[]
  with open(os.getcwd()+'/secretSanta.csv','r') as csvFile:
     csvreader=csv.reader(csvFile)
     for row in csvreader:
        rows.append(row)
  #print("rows",rows)
  for i in rows:
    dic2[i[0]]=i[1]

#print(li)  
liAll=[]
for i in li:
  liAll.extend(i)
#print(liAll)

for i in li:
   if len(i)>1:
      dic[i[0]]=i[1]
      dic1[i[1]]=i[0]

#print(dic)
#print(dic1)
#print(dic2)

#print(dic2)
  
with open(os.getcwd()+"/secretSanta.csv", 'w') as csvfile:
    
    # creating a csv writer object 
    csvwriter = csv.writer(csvfile) 
    csvwriter.writerow(["name","santa"])  
    for i in liAll:
      while True:
       name=random.choice(liAll)
       if (name!=i):
         if (name in dic1) and (dic1[name]!=i):
              if (i in dic) and (dic[i]!=name):
                  if  (i in dic2) and (dic2[i]!=name):
                     print(i,name)
                     csvwriter.writerow(list((i,name)))
                     break
                  elif i not in dic2:
                     print(i,name)
                     csvwriter.writerow(list((i,name))) 
                     break
              elif i not in dic:
                     if (i in dic2) and (dic2[i]!=name):
                       print(i,name)
                       csvwriter.writerow(list((i,name)))
                       break
                     elif i not in dic2:
                       print(i,name)
                       csvwriter.writerow(list((i,name))) 
                       break
         elif name not in dic1:
               if  (i in dic2) and (dic2[i]!=name):
                       print(i,name)
                       csvwriter.writerow(list((i,name)))
                       break
               elif i not in dic2:
                       print(i,name)
                       csvwriter.writerow(list((i,name))) 
                       break

print(os.getcwd()+"/secret.csv")

